/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2015-03-03 05:23:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("  <title>dnf地下城与勇士装备抢单器</title> \r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/button.css\" /> \r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/toolstip.css\" /> \r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/icon.css\" /> \r\n");
      out.write("  <link rel=\"shortcut icon\" href=\"http://images.5173cdn.com/images/img/ico.ico\" /> \r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/common.css\" /> \r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/fed.css\" /> \r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/page_v1.css\" /> \r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/tab_v1_1.css\" /> \r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/searchlist_v3_7.css\" /> \r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/s_ztc.css\" /> \r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/include.css\" /> \r\n");
      out.write("  <style class=\"firebugResetStyles\" type=\"text/css\" charset=\"utf-8\">/* See license.txt for terms of usage */\r\n");
      out.write("\t\r\n");
      out.write("\t.tb_head .info, .pdlist .pdlist_info {\r\n");
      out.write("\t\tpadding-left: 12px;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\twidth: 303px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.tb_head .ensure {\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\ttext-indent: 10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.tb_head .ensure, .pdlist .pdlist_ensure {\r\n");
      out.write("\t\twidth: 90px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.pdlistbox .sin_pdlbox ul.pdlist_ensure {\r\n");
      out.write("\t\theight: auto;\r\n");
      out.write("\t\tmin-height: 22px;\r\n");
      out.write("\t\twidth: 90px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tlabel{\r\n");
      out.write("\t\tfont-family: Tahoma;\r\n");
      out.write("\t\tfont-size: 12px;\r\n");
      out.write("\t\tvertical-align: middle;\r\n");
      out.write("\t\theight: 28px;\r\n");
      out.write("\t\twidth: 60px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.clearfix tr{\r\n");
      out.write("\t\theight: 25px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.pdlistbox .sin_pdlbox ul.pdlist_info li.tt a { \r\n");
      out.write("\t\tfont-size: 12px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.pdlistbox .sin_pdlbox ul.pdlist_time {\r\n");
      out.write("\t\twidth:80px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.pdlistbox .sin_pdlbox ul.pdlist_delivery {\r\n");
      out.write("\t\twidth:165px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.header_box {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tpadding:20px 0px 0px 0px;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write(".pdlistbox .sin_pdlbox ul.pdlist_ensure li {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    width: 65px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\t</style> \r\n");
      out.write("  <script type=\"text/javascript\" src=\"js/jquery-1.5.2.min.js\" charset=\"utf-8\"></script> \r\n");
      out.write("  <script language=\"JavaScript\" type=\"text/javascript\" src=\"js/s-ztc.js\"></script> \r\n");
      out.write("  <script type=\"text/javascript\">document.domain = \"5173.com\";</script> \r\n");
      out.write("  <script src=\"http://urchin.5173.com/urchin.js\" type=\"text/javascript\"></script> \r\n");
      out.write(" </head> \r\n");
      out.write(" <body> \r\n");
      out.write("  <div class=\"header\"> \r\n");
      out.write("   <!-- 顶部登陆条+快捷菜单条 -->\r\n");
      out.write("   <!--网站Logo+四级联动搜索条 border:1px solid #FF88C2; --> \r\n");
      out.write("   <div class=\"header_box clearfix\"> \r\n");
      out.write("    <form id=\"gsForm\" method=\"get\" class=\"clearfix\"> \r\n");
      out.write("     <div id=\"userinfo\" style=\"font-size: 12px;\"> \r\n");
      out.write("      <table width=\"947\" border=\"0\"> \r\n");
      out.write("       <tbody>\r\n");
      out.write("        <tr> \r\n");
      out.write("         <td>5173帐号：</td> \r\n");
      out.write("         <td>选择游戏：</td> \r\n");
      out.write("         <td>收货角色：</td> \r\n");
      out.write("         <td>选择客服：</td> \r\n");
      out.write("         <td><input type=\"button\" id=\"startscan\" value=\"开始扫描\" style=\"width:240px;\" /></td> \r\n");
      out.write("        </tr> \r\n");
      out.write("        <tr> \r\n");
      out.write("         <td><input type=\"text\" id=\"gameusername\" style=\"width:160px;\" /></td> \r\n");
      out.write("         <td> <select name=\"gametype\" style=\"width:160px;\"> <option value=\"dnf\">dnf</option> </select> </td> \r\n");
      out.write("         <td><input type=\"text\" id=\"txtGameRole\" style=\"width:160px;\" /></td> \r\n");
      out.write("         <td> <select id=\"customer\" style=\"width:160px;\"> <option value=\"Star1\">一星</option> <option value=\"Star5\">五星</option> </select> </td> \r\n");
      out.write("         <td><input type=\"button\" id=\"stopscan\" value=\"停止扫描\" style=\"width:240px;\" /></td> \r\n");
      out.write("        </tr> \r\n");
      out.write("        <tr> \r\n");
      out.write("         <td>5173密码：</td> \r\n");
      out.write("         <td>选择区：</td> \r\n");
      out.write("         <td>角色等级：</td> \r\n");
      out.write("         <td>价格大于等于：</td> \r\n");
      out.write("         <td rowspan=\"7\"><textarea id=\"outputPanel\" style=\"width:240px;height:175px;font-size: 10px\"></textarea></td> \r\n");
      out.write("        </tr> \r\n");
      out.write("        <tr> \r\n");
      out.write("         <td><input type=\"password\" id=\"password\" style=\"width:160px;\" /></td> \r\n");
      out.write("         <td> <select name=\"gamedistict\" style=\"width:160px;\"> <option value=\"alldis\">全部区</option> </select> </td> \r\n");
      out.write("         <td><input type=\"text\" id=\"rolelevel\" style=\"width:160px;\" /></td> \r\n");
      out.write("         <td><input type=\"text\" id=\"minprice\" style=\"width:160px;\" /></td> \r\n");
      out.write("        </tr> \r\n");
      out.write("        <tr> \r\n");
      out.write("         <td><input type=\"button\" id=\"logingame\" value=\"登录5173\" style=\"width:160px;\" /></td> \r\n");
      out.write("         <td>选择服：</td> \r\n");
      out.write("         <td>联系电话：</td> \r\n");
      out.write("         <td>信誉小于等于：</td> \r\n");
      out.write("        </tr> \r\n");
      out.write("        <tr> \r\n");
      out.write("         <td> <input type=\"checkbox\" id=\"radio\" checked=\"checked\" />开启新单声音提醒 </td> \r\n");
      out.write("         <td> <select name=\"gameservice\" style=\"width:160px;\"> <option value=\"alldis\">全部服</option> </select> </td> \r\n");
      out.write("         <td><input type=\"text\" id=\"txtBuyerTel\" style=\"width:160px;\" /></td> \r\n");
      out.write("         <td><select id=\"creditlevel\" style=\"width:160px;\">  <option value=\"1\">一星</option> <option value=\"2\">二星</option><option value=\"3\" selected=\"selected\">三星</option> </select></td> \r\n");
      out.write("        </tr> \r\n");
      out.write("        <tr> \r\n");
      out.write("         <td> <input type=\"checkbox\" id=\"toshop\" />下单后自动打开付款界面 </td> \r\n");
      out.write("         <td>选择问题;</td> \r\n");
      out.write("         <td>问题答案：</td> \r\n");
      out.write("         <td>联系QQ;</td> \r\n");
      out.write("        </tr> \r\n");
      out.write("        <tr> \r\n");
      out.write("         <td> <input type=\"checkbox\" id=\"allauto\" />开启一键付款功能（需开通） </td> \r\n");
      out.write("         <td> <select name=\"selectprob\" style=\"width:160px;\"> <option value=\"fathername\">您父亲的名字是？</option> </select> </td> \r\n");
      out.write("         <td><input type=\"text\" id=\"ans\" style=\"width:160px;\" /></td> \r\n");
      out.write("         <td><input type=\"text\" id=\"txtBuyerQQ\" style=\"width:160px;\" /></td> \r\n");
      out.write("        </tr> \r\n");
      out.write("         <tr> \r\n");
      out.write("         <td> <label id=\"query\" style=\"width:160px;\"></label> </td> \r\n");
      out.write("         <td> <label id=\"avrtime\" style=\"width:160px;\"></label> </td> \r\n");
      out.write("         <td colspan=3> <label  style=\"width:160px;\"></label> </td> \r\n");
      out.write("        </tr> \r\n");
      out.write("       </tbody>\r\n");
      out.write("      </table> \r\n");
      out.write("     </div> \r\n");
      out.write("    </form> \r\n");
      out.write("   </div> \r\n");
      out.write("   <script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("    function Login(loginType) {\r\n");
      out.write("        if (loginType == \"common\")\r\n");
      out.write("            window.location = \"https://passport.5173.com/?UnDecode=1&returnUrl=\" + escape(window.location.href);\r\n");
      out.write("        else if (loginType == \"qq\")\r\n");
      out.write("            window.location = \"https://passport.5173.com/Partner/LoginFrom?UnDecode=1&appNo=qq&returnUrl=\" + escape(window.location.href);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("</script> \r\n");
      out.write("     <!--<p id=\"query\"></p>\r\n");
      out.write("    <p id=\"avrtime\"></p>\r\n");
      out.write("    <p id=\"session\"> ");
      out.print("Session ID = " + session.getId() );
      out.write(" </p>\r\n");
      out.write("    <div id=\"outputPanel\"></div>   -->\r\n");
      out.write("   <div class=\"search-body clearfix\"> \r\n");
      out.write("    <div class=\"layout\"> \r\n");
      out.write("     <div class=\"tab_v1_1 v2\"></div> \r\n");
      out.write("     <div class=\"mainbody\"> \r\n");
      out.write("      <div class=\"sort_box\"></div> \r\n");
      out.write("      <script type=\"text/javascript\" src=\"http://img01.5173cdn.com/fed/build/1.00/js/fed.share.js\"></script> \r\n");
      out.write("      <div class=\"pdlist equipment_list\"> \r\n");
      out.write("       <ul id=\"headerForEquipment\" class=\"tb_head equipment_head sort_bottom1\"> \r\n");
      out.write("        <li class=\"info\">标题</li> \r\n");
      out.write("        <li class=\"price\">价格</li> \r\n");
      out.write("        <li class=\"ensure\" style=\" width: 85px;\">下单</li> \r\n");
      out.write("        <li class=\"num\" style=\"width:100px\">区服</li> \r\n");
      out.write("        <li class=\"ensure\" style=\"width:80px\">卖家信用</li> \r\n");
      out.write("        <li class=\"delivery\" style=\"width: 150px;\">订单编号</li> \r\n");
      out.write("        <li class=\"delivery\" style=\"width: 120px;\">更新时间</li> \r\n");
      out.write("       </ul> \r\n");
      out.write("       <div class=\"pdlistbox\" id=\"resultlist\"> \r\n");
      out.write("        \r\n");
      out.write("       </div> \r\n");
      out.write("      </div> \r\n");
      out.write("     </div> \r\n");
      out.write("    </div> \r\n");
      out.write("   </div> \r\n");
      out.write("   <div class=\"blank10\"></div> \r\n");
      out.write("  </div> \r\n");
      out.write("  <script type=\"text/javascript\" src=\"js/fed-min.js\"></script> \r\n");
      out.write("  <script type=\"text/javascript\" src=\"js/fed.follow.js\"></script> \r\n");
      out.write("  <script type=\"text/javascript\" src=\"js/search/search_v36a.js\" charset=\"utf-8\"></script> \r\n");
      out.write("  <script type=\"text/javascript\" src=\"js/fed-std/layer/v1/popup_layer.js\" charset=\"utf-8\"></script> \r\n");
      out.write("  <!-- WiseMedia检测代码 --> \r\n");
      out.write("  <script type=\"text/javascript\" src=\"http://aw.kejet.net/t?p=K0&amp;c=vp&amp;er=1&amp;kd=1&amp;sid=1730880509812150273&amp;zid=1730880509812150272\"></script> \r\n");
      out.write("  <script type=\"text/javascript\" src=\"js/jquery.json-2.4.min.js\"></script> \r\n");
      out.write("  <script type=\"text/javascript\" src=\"js/common.js\"></script> \r\n");
      out.write("  <script type=\"text/javascript\" src=\"js/goodslist.js\"></script>   \r\n");
      out.write("  <script type=\"text/javascript\">  \r\n");
      out.write("        var infoPanel = document.getElementById('resultlist'); // 输出结果面板  \r\n");
      out.write("        var outputPanel = document.getElementById('outputPanel'); // 输出结果面板  \r\n");
      out.write("        var query = document.getElementById('query'); \r\n");
      out.write("        var avrtime = document.getElementById('avrtime'); \r\n");
      out.write("        var sendButton = document.getElementById('startscan');// \r\n");
      out.write("        var stopButton = document.getElementById('stopscan');// \r\n");
      out.write("        var loginButton = document.getElementById('logingame');//\r\n");
      out.write("        var radioButton = document.getElementById('radio');// \r\n");
      out.write("           // 控制台输出对象  \r\n");
      out.write("        var console = {log : function(text) {\r\n");
      out.write("        \t    if(text.indexOf(\"grabber_query\") != -1){\r\n");
      out.write("        \t    \tquery.innerHTML = text.substring(text.indexOf(\"grabber_query\")+\"grabber_query\".length);\r\n");
      out.write("        \t    }else if(text.indexOf(\"grabber_avrtime\") != -1){\r\n");
      out.write("        \t    \tavrtime.innerHTML = text.substring(text.indexOf(\"grabber_avrtime\")+\"grabber_avrtime\".length);\r\n");
      out.write("        \t    }else if(text.indexOf(\"grabber_node\") != -1){\r\n");
      out.write("        \t    \tinfoPanel.innerHTML = text.substring(text.indexOf(\"grabber_node\")+\"grabber_node\".length) + \"<br>\"+infoPanel.innerHTML ;\r\n");
      out.write("        \t    }else{\r\n");
      out.write("        \t    \toutputPanel.innerHTML = text+ \"\\n\"+outputPanel.innerHTML;\r\n");
      out.write("        \t    }\r\n");
      out.write("        \t}};  \r\n");
      out.write("        // WebSocket演示对象  \r\n");
      out.write("        var demo = {  \r\n");
      out.write("            socket : null,  // WebSocket连接对象  \r\n");
      out.write("            host : '',      // WebSocket连接 url  \r\n");
      out.write("            connect : function() {  // 连接服务器  \r\n");
      out.write("                window.WebSocket = window.WebSocket || window.MozWebSocket;  \r\n");
      out.write("                if (!window.WebSocket) {    // 检测浏览器支持  \r\n");
      out.write("                    console.log('Error: WebSocket is not supported .');  \r\n");
      out.write("                    return;  \r\n");
      out.write("                }  \r\n");
      out.write("                this.socket = new WebSocket(this.host); // 创建连接并注册响应函数  \r\n");
      out.write("                this.socket.onopen = function(){\r\n");
      out.write("                \tconsole.log(\"开始成功。。。\");\r\n");
      out.write("                \tlogingame();\r\n");
      out.write("                };  \r\n");
      out.write("                this.socket.onmessage = function(message) {\r\n");
      out.write("                \tconsole.log(message.data);\r\n");
      out.write("                \t};  \r\n");
      out.write("                this.socket.onclose = function(){  \r\n");
      out.write("                    console.log(\"服务器已关闭\");  \r\n");
      out.write("                    demo.socket = null; // 清理  \r\n");
      out.write("                };  \r\n");
      out.write("            },  \r\n");
      out.write("            send : function(message) {  // 发送消息方法  \r\n");
      out.write("                if (this.socket) {  \r\n");
      out.write("                    this.socket.send(message);  \r\n");
      out.write("                    return true;  \r\n");
      out.write("                }  \r\n");
      out.write("                console.log('请先连接服务器!!!');  \r\n");
      out.write("                return false;  \r\n");
      out.write("            }  \r\n");
      out.write("        };  \r\n");
      out.write("        // 初始化WebSocket连接 url  \r\n");
      out.write("        demo.host=(window.location.protocol == 'http:') ? 'ws://' : 'wss://' ;  \r\n");
      out.write("        demo.host += window.location.host + '/grabber/websocket/say';  \r\n");
      out.write("        \r\n");
      out.write("       /* connButton.onclick = function() {  \r\n");
      out.write("            if (!demo.socket)   demo.connect();  \r\n");
      out.write("            else console.log('websocket already exists .');  \r\n");
      out.write("        };*/ \r\n");
      out.write("     // 初始化按钮点击事件函数  \r\n");
      out.write("        sendButton.onclick = function() {\r\n");
      out.write("           // var message =\"{action:start,msg:{creditlevel:3}}\";  \r\n");
      out.write("           if (!demo.socket)   demo.connect();\r\n");
      out.write("            var message ={}; \r\n");
      out.write("        \tvar params={};\r\n");
      out.write("\t\t\tparams.creditlevel=document.getElementById('creditlevel').value;\r\n");
      out.write("\t\t\tparams.minprice=document.getElementById('minprice').value;\r\n");
      out.write("\t\t\tparams.radio=document.getElementById('radio').checked;\r\n");
      out.write("\t\t\tmessage.action=\"start\";\r\n");
      out.write("\t\t\tmessage.msg=params;\r\n");
      out.write("\t\t\tif (!message) return;  \r\n");
      out.write("            if (!demo.send(JSON.stringify(message))) return; \r\n");
      out.write("        }; \r\n");
      out.write("        stopButton.onclick = function() {\r\n");
      out.write("            var message =\"{action:stop,msg:{creditlevel:3}}\";  \r\n");
      out.write("            if (!message) return;  \r\n");
      out.write("            if (!demo.send(message)) return;  \r\n");
      out.write("        };  \r\n");
      out.write("        loginButton.onclick = function() {\r\n");
      out.write("        \tautoConn();\r\n");
      out.write("        };   \r\n");
      out.write("        radioButton.onclick = function() {\r\n");
      out.write("        \tvar message ={}; \r\n");
      out.write("        \tvar params={};\r\n");
      out.write("\t\t\tparams.radio=document.getElementById('radio').checked;  \r\n");
      out.write("        \tmessage.action=\"play\";\r\n");
      out.write("\t\t\tmessage.msg=params;\r\n");
      out.write("\t\t\tif (!message) return;  \r\n");
      out.write("            if (!demo.send(JSON.stringify(message))) return;  \r\n");
      out.write("        }; \r\n");
      out.write("        function logingame(){\r\n");
      out.write("        \tvar message ={}; \r\n");
      out.write("        \tvar params={};\r\n");
      out.write("\t\t\tparams.txtGameRole=document.getElementById('txtGameRole').value;\r\n");
      out.write("\t\t\tparams.rolelevel=document.getElementById('rolelevel').value;\r\n");
      out.write("\t\t\tparams.txtBuyerTel=document.getElementById('txtBuyerTel').value;\r\n");
      out.write("\t\t\tparams.txtBuyerQQ=document.getElementById('txtBuyerQQ').value;\r\n");
      out.write("\t\t\tparams.customer=document.getElementById('customer').value;\r\n");
      out.write("\t\t\tparams.username=document.getElementById('gameusername').value;\r\n");
      out.write("\t\t\tparams.password=document.getElementById('password').value;\r\n");
      out.write("\t\t\t//if (!check(message)) return;\r\n");
      out.write("\t\t\tmessage.action=\"login\";\r\n");
      out.write("\t\t\tmessage.msg=params;\r\n");
      out.write("\t\t\tif (!message) return;  \r\n");
      out.write("            if (!demo.send(JSON.stringify(message))) return; \r\n");
      out.write("        }\r\n");
      out.write("        function shop(params) {\r\n");
      out.write("        \tvar message ={}; \r\n");
      out.write("        \tmessage.action=\"shop\";\r\n");
      out.write("        \tmessage.msg=params;\r\n");
      out.write("            if (!message) return;  \r\n");
      out.write("            if (!demo.send(JSON.stringify(message))) return;  \r\n");
      out.write("        };  \r\n");
      out.write("        function autoConn(){  \r\n");
      out.write("            if (!demo.socket)   demo.connect();  \r\n");
      out.write("            else{\r\n");
      out.write("            \t//console.log('websocket already exists .');  \r\n");
      out.write("            \tlogingame();\r\n");
      out.write("            } \r\n");
      out.write("        }; \r\n");
      out.write("        \r\n");
      out.write("    </script>  \r\n");
      out.write(" </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
