/*begin
2014-12-30 08:10:36 By wd@5173.com*/
function selectSortCss(a){if(a=jQuery("#"+a).val()){jQuery("#orderLabel span").hide();jQuery("#orderLabel").find("."+a).show()}}
$(document).ready(function(){$(".sin_pdlbox").each(function(e){this.style.background=["#ffffff","#fbfbfb"][e%2]});$(".sin_pdlbox").hover(function(){$(this).addClass("yellow")},function(){$(this).removeClass("yellow")});$("#SZsinBox .sin_pdlbox").hover(function(){$(this).children(".anglebox").show();$(this).parent(".hot_recobox").css("z-index","11");$(this).css("z-index","11")},function(){$(this).children(".anglebox").hide();$(this).parent(".hot_recobox").css("z-index","10");$(this).css("z-index",
"10")});jQuery("#orderLabel").bind("mouseenter",function(){clearTimeout(window.ccc);jQuery("#orderFrame").show()});jQuery("#orderFrame").bind("mouseenter",function(){clearTimeout(window.ccc)});jQuery("#orderFrame").bind("mouseleave",function(){jQuery("#orderFrame").hide()});jQuery("#orderLabel").bind("mouseleave",function(){window.ccc=setTimeout(function(){jQuery("#orderFrame").hide()},100)});jQuery("#UED_more").bind("mouseover",function(){jQuery(this).find(".more_pop").show()}).bind("mouseout",function(){jQuery(this).find(".more_pop").hide()});
jQuery("#SelectSortCss").val()?selectSortCss("SelectSortCss"):jQuery("#orderFrame li").each(function(){jQuery(this).bind("click",function(){jQuery("#orderLabel span").hide();var e=jQuery(this).find("a").attr("class");jQuery("#SelectSortCss").val(e);jQuery("#orderLabel").find("."+e).show();jQuery("#orderFrame").hide()})});var a=["UED_all","UED_gameid","UED_equipment","UED_money","UED_insteadt","UED_card","UED_level","UED_code","UED_other"];jQuery("#UED_all").bind("click",function(){jQuery.each(a,function(e,
b){jQuery("#"+b).attr("class","");jQuery("#"+b+"body").hide()});jQuery("#UED_all").attr("class","current");jQuery("#UED_allbody").show()});jQuery("#UED_gameid").bind("click",function(){jQuery.each(a,function(e,b){jQuery("#"+b).attr("class","");jQuery("#"+b+"body").hide()});jQuery("#UED_gameid").attr("class","current");jQuery("#UED_gameidbody").show()});jQuery("#UED_equipment").bind("click",{id:"comment"},function(){jQuery.each(a,function(e,b){jQuery("#"+b).attr("class","");jQuery("#"+b+"body").hide()});
jQuery("#UED_equipment").attr("class","current");jQuery("#UED_equipmentbody").show()});jQuery("#UED_money").bind("click",{id:"comment"},function(){jQuery.each(a,function(e,b){jQuery("#"+b).attr("class","");jQuery("#"+b+"body").hide()});jQuery("#UED_money").attr("class","current");jQuery("#UED_moneybody").show()});jQuery("#UED_code").bind("click",{id:"comment"},function(){jQuery.each(a,function(e,b){jQuery("#"+b).attr("class","");jQuery("#"+b+"body").hide()});jQuery("#UED_code").attr("class","current");
jQuery("#UED_codebody").show()});jQuery("#UED_level").bind("click",{id:"comment"},function(){jQuery.each(a,function(e,b){jQuery("#"+b).attr("class","");jQuery("#"+b+"body").hide()});jQuery("#UED_level").attr("class","current");jQuery("#UED_levelbody").show()});jQuery("#UED_insteadt").bind("click",{id:"comment"},function(){jQuery.each(a,function(e,b){jQuery("#"+b).attr("class","");jQuery("#"+b+"body").hide()});jQuery("#UED_insteadt").attr("class","current");jQuery("#UED_insteadtbody").show()});jQuery("#UED_card").bind("click",
{id:"comment"},function(){jQuery.each(a,function(e,b){jQuery("#"+b).attr("class","");jQuery("#"+b+"body").hide()});jQuery("#UED_card").attr("class","current");jQuery("#UED_cardbody").show()});jQuery("#UED_other").bind("click",{id:"other"},function(){jQuery.each(a,function(e,b){jQuery("#"+b).attr("class","");jQuery("#"+b+"body").hide()});jQuery("#UED_other").attr("class","more_on");jQuery("#UED_otherbody").show()});jQuery("#ensure").bind("mouseenter",function(){clearTimeout(window.aaa);jQuery("#ensureFrame").show();
jQuery("#ensure").addClass("typeboxhover")});jQuery("#ensureFrame").bind("mouseenter",function(){clearTimeout(window.aaa)});jQuery("#ensureFrame").bind("mouseleave",function(){jQuery("#ensureFrame").hide();jQuery("#ensure").removeClass("typeboxhover")});jQuery("#ensure").bind("mouseleave",function(){window.aaa=setTimeout(function(){jQuery("#ensureFrame").hide();jQuery("#ensure").removeClass("typeboxhover")},100)});jQuery("#status").bind("mouseenter",function(){clearTimeout(window.aaa);jQuery("#statusFrame").show();
jQuery("#status").addClass("typeboxhover")});jQuery("#statusFrame").bind("mouseenter",function(){clearTimeout(window.aaa)});jQuery("#statusFrame").bind("mouseleave",function(){jQuery("#statusFrame").hide();jQuery("#status").removeClass("typeboxhover")});jQuery("#status").bind("mouseleave",function(){window.aaa=setTimeout(function(){jQuery("#statusFrame").hide();jQuery("#status").removeClass("typeboxhover")},100)});jQuery("#baozhang").bind("mouseenter",function(){clearTimeout(window.bbb);jQuery("#baozhangFrame").show();
jQuery("#baozhang").addClass("ensboxhover")});jQuery("#baozhang").bind("mouseleave",function(){window.bbb=setTimeout(function(){jQuery("#baozhangFrame").hide();jQuery("#baozhang").removeClass("ensboxhover")},100)});jQuery("#baozhangFrame").bind("mouseenter",function(){clearTimeout(window.bbb)});jQuery("#baozhangFrame").bind("mouseleave",function(){jQuery("#baozhangFrame").hide();jQuery("#baozhang").removeClass("ensboxhover")});jQuery("#baozhangFrame li").hover(function(){jQuery(this).addClass("on")},
function(){jQuery(this).removeClass("on")});jQuery("#Recommend").bind("mouseenter",function(){clearTimeout(window.bbb);jQuery("#recomFrame").show();jQuery("#Recommend").addClass("current")});jQuery("#Recommend").bind("mouseleave",function(){window.ccc=setTimeout(function(){jQuery("#recomFrame").hide();jQuery("#Recommend").removeClass("current")},100)});jQuery("#recomFrame").bind("mouseenter",function(){clearTimeout(window.ccc)});jQuery("#recomFrame").bind("mouseleave",function(){jQuery("#recomFrame").hide();
jQuery("#Recommend").removeClass("current")});jQuery("#ensureFrame li").click(function(){$("#ensure").removeClass("typeboxhover");jQuery("#ensureFrame").hide()});jQuery("#UED_all2").bind("click",function(e){e.stopPropagation();jQuery(this).attr("checked")?jQuery("#baozhangFrame li input").attr("checked",true):jQuery("#baozhangFrame li input").attr("checked",false)});jQuery("#bz_all_btn").bind("click",function(){$("#baozhangFrame input:checked").parent().attr("class")?$("#baozhang_em").attr("class",
$("#baozhangFrame input:checked").parent().attr("class")):$("#baozhang_em").attr("class","");$("#baozhang").parent().removeClass("ensboxhover");$("#baozhangFrame").hide()});jQuery("#UED_text_server_name_1").val("\u8bf7\u8f93\u5165\u4e2d\u6587\u540d\u6216\u62fc\u97f3\u9996\u5b57\u6bcd").focus(function(){$(this).val()=="\u8bf7\u8f93\u5165\u4e2d\u6587\u540d\u6216\u62fc\u97f3\u9996\u5b57\u6bcd"&&$(this).val("")}).blur(function(){$(this).val()==""&&$(this).val("\u8bf7\u8f93\u5165\u4e2d\u6587\u540d\u6216\u62fc\u97f3\u9996\u5b57\u6bcd")});
var c=[],h=[];$(".has_popup").each(function(e){c[e]={};h[e]={};c[e].blk1=new PopupLayer({trigger:this,popupBlk:$(this).attr("id")+"_1",eventType:"mouseover",offsets:{x:0,y:-30}});c[e].blk1.popupLayer.css({"z-index":3,width:this.offsetWidth});c[e].blk1.popupIframe.css({width:this.offsetWidth});c[e].blk1.popupBlk.children().text($(this).text());c[e].blk2=new PopupLayer({trigger:this,popupBlk:$(this).attr("id")+"_2",eventType:"mouseover",offsets:{x:0,y:-1},onBeforeStart:function(){var b=$(this.trigger.attr("id")+
"_2");b.show();var g=b.find("ul")[0].clientWidth;b.hide();if(this.trigger.offset().left+g>$(".crumbs").offset().left+$(".crumbs").width())this.options.offsets.x=$(".crumbs").offset().left+$(".crumbs").width()-g-this.trigger.offset().left-2}});h[e]=$(document.createElement("div")).addClass("wrap"+e).appendTo("body").append(c[e].blk1.popupLayer).append(c[e].blk2.popupLayer);h[e].bind("mouseleave",function(){$(this).children().hide()})});$(".goods_img_box").hover(function(){var e=$(this).find(".big_img_box"),
b=e.find("img");$(this).css({position:"relative"}).parent(".sin_pdlbox").css({zIndex:"2"});e.show();if(b.hasClass("load_img")){e=new Image;e.onload=function(){b.attr("src",this.src).attr("lazyloadsrc","").removeClass("load_img")};e.src=b.attr("lazyloadsrc")}},function(){$(this).css({position:""}).parent(".sin_pdlbox").css({zIndex:"1"}).find(".big_img_box").hide()})});
function nonceShowHide(a,c){if(jQuery("#"+a+"Frame").css("display")=="block"){jQuery("#"+a+"Frame").hide();jQuery("#"+a).removeClass("n_on").addClass("n_off")}else{jQuery("#"+a+"Frame").show();var h=$('<iframe frameborder="0" border="0" style="position: absolute; z-index: 99; right: 0px; top: 20px; width: 113px; height: 272px;"></iframe>').appendTo($(c).parent().parent());jQuery("#"+a).removeClass().addClass("n_on");jQuery("#"+a+"Frame").width($("#"+a).width()>111?$("#"+a).width()+15:111);jQuery("#"+
a+"Frame ul li a").click(function(){jQuery("#"+a+"Frame").hide();jQuery("#"+a).removeClass("n_on").addClass("n_off");jQuery("#"+a).html(jQuery(this).parent().html()+"<span class=Icon_1 onclick=nonceShowHide('"+a+"')></span>")});jQuery("#"+a+"Frame").mouseover(function(){jQuery(this).show();h.show();jQuery("#"+a).removeClass().addClass("n_on")});jQuery("#"+a+"Frame").mouseleave(function(){jQuery(this).hide();h.hide();jQuery("#"+a).removeClass().addClass("n_off");setTimeout(function(){jQuery("#"+a).unbind("mouseover")},
500)});jQuery("#"+a).mouseover(function(){jQuery("#"+a+"Frame").show();h.show();jQuery("#"+a).removeClass().addClass("n_on")});jQuery("#"+a).mouseleave(function(){jQuery("#"+a+"Frame").hide();h.hide();jQuery("#"+a).removeClass().addClass("n_off");setTimeout(function(){jQuery("#"+a).unbind("mouseover")},500)})}}
$(function(){$(".push").click(function(a,c){a=!c?$(this):$(c);if(a.html()=="\u663e\u793a\u5168\u90e8"){a.html("\u7cbe\u7b80\u663e\u793a");a.closest(".choosebody").find("dl").height("auto");a.attr("class","push_up")}else{a.html("\u663e\u793a\u5168\u90e8");a.closest(".choosebody").find("dl").height("");a.attr("class","push")}}).trigger("clickmore");$(".showaddlink").click(function(){var a=$(this);$(a).html()=="\u663e\u793a\u5168\u90e8"?$("#J_nofind").hide():$("#J_nofind").show()})});
function floatdiv(a,c){var h={offset:480,top:100};if(c!=null)h=$.extend(h,c);c=h.offset;if(c<0)c-=$(a).width();if($.browser.msie&&$.browser.version=="6.0"){$("body").css({"background-image":"url(about:blank)","background-attachment":"fixed"});$(a).attr("style","position:absolute;  left:50%; top:expression(eval(document.documentElement.scrollTop + "+h.top+")); margin-left:"+c+"px;")}else $(a).css({position:"fixed",left:"50%",top:h.top+"px","margin-left":c+"px"})}
$("#scrollRight").css({top:"55px",position:"absolute",left:"50%",margin:"0 0 0 500px"});$("#scrollRight .feedback").css("width","90px");$("#scrollRight .feedback").css("padding-bottom","70px");$("#scrollRight .feedback a").css("width","90px");$("#scrollRight .feedback a").css("height","70px");$("#scrollRight .feedback a").attr("href","http://sc.5173.com/index.php?question/ask_skip.html");$("#scrollRight .feedback a").css("background-image","url(http://img01.5173cdn.com/channel/build/1.00/images/suggestion_box.gif)");
function fixedslide(a,c){var h=$.browser.msie&&$.browser.version==="6.0";if(c)var e=c.offset,b=c.top;$(a).css({position:"fixed",left:"50%","margin-left":e,top:b,position:"absolute"});h||$(window).scroll(function(){$(this).scrollTop()<parseInt(b)?$(a).css({position:"absolute",top:b}):$(a).css({position:"fixed",top:"0"})})}
var vote_entrance={isIE6:navigator.userAgent.toLowerCase().indexOf("msie 6.0")!==-1,show:function(a){a=$("<div></div>").html(a);this.isIE6?a.css({position:"absolute",left:"0",top:"300px",zIndex:"998"}):a.css({position:"fixed",left:"0",top:"300px",zIndex:"998"});$("body").append(a)}};
$(function(){$(window).height();$("div .header").height();$("div .place").height();$("div .sifting").height();$("div .filterbox").height();$("#divTest").height();var a=function(c,h){c=typeof c==="string"?document.getElementById(c):c;h=h||2E3;var e=c.clientHeight,b=c.getElementsByTagName("ul").length,g,j=function(){c.scrollTop+=1;if(c.scrollTop===e*b)c.scrollTop=0;g=c.scrollTop%e===0?setTimeout(arguments.callee,h):setTimeout(arguments.callee,50)};c.innerHTML+=c.innerHTML;g=setTimeout(j,h);c.onmouseover=
function(){clearTimeout(g);g=null};c.onmouseout=function(){g=setTimeout(j,h)}};$("#turnoverCenter").length&&a("turnoverCenter",1500)});
(function(a){function c(j){return a.ajax({type:"get",url:"http://sales.5173.com/ajax/ajaxinfo.aspx?method=GetTradingTipsInfo&params="+j,dataType:"jsonp",jsonpCallback:"callbackdt",jsonp:"jsoncallback"})}function h(j,m){var n="";n='<dl><dt>\u5356\u5bb6\u4fe1\u606f</dt><dd><span class="f_666">\u5356\u5bb6\u597d\u8bc4\u6570\uff1a</span>'+j.GoodReviewCount+'\u7b14</dd><dd><span class="f_666">\u65e0\u8d27\u8d54\u4ed8\u7387\uff1a</span>'+j.NoGoodsRate+'</dd><dd><span class="f_666">\u8d85\u65f6\u8d54\u4ed8\u7387\uff1a</span>'+
j.TimeOutRate+'</dd><dd><span class="f_666">\u6708\u6210\u4ea4\u7b14\u6570\uff1a</span>'+j.TradeCount+'\u7b14</dd><dd><span class="f_666">\u5546\u57ce\u5165\u9a7b\u65f6\u95f4\uff1a</span>'+j.SettledDate+'</dd></dl><a href="http://mall.5173.com/EasyBuy/EvaluateInfo.aspx?productid='+m+'" class="xy_link">\u4fe1\u7528\u8be6\u60c5</a>';a(b.floatDiv).find("div.span_m").html(n)}function e(j){var m,n={},i,l;a.extend(b,j);if(a(b.tar).length&&a(b.tar).attr("data")){a(b.floatDiv).length?a(b.floatDiv).find("div.span_m").html(b.html):
a("body").append('<div class="'+b.floatDiv.replace(/[\.\#]/g,"")+'" style="display:none"><div class="span_m">'+b.html+'</div><span class="anglecorner"> <em>\u25c6</em><span class="angleboxpic">\u25c6</span></span></div>');a("body").delegate(b.tar,"hover",function(o){var d=a(this).offset(),f=a(this).attr("data");if(a(this).attr("data"))if(o.type==="mouseenter"){clearTimeout(l);a(b.floatDiv).css({top:d.top+b.preTop,left:d.left+b.preLeft}).show().find("div.span_m").html(b.html);if(n[f])h(n[f],f);else i=
setTimeout(function(){m=c(f);m.done(function(k){n[f]=k[0];h(n[f],f)})},b.showDelay)}else{m&&m.readyState&&m.abort();clearTimeout(i);l=setTimeout(function(){a(b.floatDiv).hide()},b.hideDelay)}});a("body").delegate(b.floatDiv,"hover",function(o){o.type==="mouseenter"?clearTimeout(l):a(this).hide()})}}var b={html:'<img style="display:block;margin:0 auto;"  src="http://img01.5173cdn.com/fed/build/1.00/images/tips_loading.gif"/>',tar:"div.hot_recommend div.sin_pdlbox",floatDiv:".anglebox",preLeft:-1,preTop:20,
showDelay:300,hideDelay:300};a.showSellerOrderInfo=e;var g={defOpt:{singleBox:".sing_filbox",parentBox:".filterbox",ctrlDom:".multi-ctrl"}};g.setPosition=function(j){var m=a(j),n=g.toDefault();return function(){var i=m.closest(g.defOpt.singleBox),l=i.closest(g.defOpt.parentBox),o,d;if(i.next().length){o=i.next();d="paddingTop"}else{o=l;d="paddingBottom"}i.offset();l.offset();if(m.attr("class")==="multi-close"){i.removeAttr("style").css({left:0});o.removeAttr("style").css(d,i.height()+15)}else n()}};
g.toDefault=function(){var j=a(g.defOpt.ctrlDom).closest(g.defOpt.singleBox),m;return function(){m=j.find("input.multi-checkbox:checked");j.closest(g.defOpt.parentBox+"[style]").removeAttr("style");a.each(m,function(){a(this).is(":checked")&&a(this).attr("checked",false)});a.each(j.siblings(),function(){a(this).attr("style")&&a(this).removeAttr("style");a(this).is(".multi-on")&&a(this).removeClass("multi-on")});j.find(".multi-submit a").attr("class","btnlink_w_small err");j.find(".multi-close").attr("class",
"multi-select").html("<strong>+</strong>\u591a\u9009");j.find('a[class^="push"]').attr("class","push").html("\u663e\u793a\u5168\u90e8");j.children(".choosebody").find("dl").height("")}};g.init=function(j){j&&a.extend(g.defOpt,j);var m={"multi-select":"<strong>+</strong>\u591a\u9009","multi-close":"\u5173\u95ed"},n=g.toDefault();a(".choosebody").delegate("a","click",function(i){a(this).closest(g.defOpt.singleBox).is(".multi-on")&&i.preventDefault()});a(g.defOpt.ctrlDom).delegate("a","click",function(i){i.preventDefault();
i=a(this);var l=i.closest(g.defOpt.singleBox),o=i.attr("class"),d=g.setPosition(this);n();if(o.match("multi-select")){i.attr("class","multi-close").html(m[i.attr("class")]);l.addClass("multi-on")}else{i.attr("class","multi-select").html(m[i.attr("class")]);l.removeClass("multi-on")}d()});a(".choosebody").delegate(".multi-checkbox","click",function(){var i=a(this).closest(g.defOpt.singleBox).find(".multi-checkbox"),l=a(this).closest(g.defOpt.singleBox).find(".multi-submit a");a.each(i,function(o,d){if(a(d).is(":checked")){l.attr("class",
"btnlink_o_s_small");return false}else l.attr("class","btnlink_w_small err")})});a(".push").bind("clickmore",function(){var i=a(".multi-on"),l;if(i.length){l=i.offset();i.css("top",l.top)}})};a.multiControle=g})(jQuery);
$(function(){$(".sort_top > li").hover(function(){var a=$(this).find("div.dbbox-pop");if(a.length){if(!parseInt(a.css("top"))){var c=a.height()+5;a.css({top:"-"+c+"px"})}a.show();$(this).parent().css("z-index","100").parent().css("z-index","100").parent().css("z-index","100")}},function(){var a=$(this).find("div.dbbox-pop");if(a.length){a.hide();$(this).parent().css("z-index","").parent().css("z-index","").parent().css("z-index","")}});$.showSellerOrderInfo();$.multiControle.init()});
$(function(){function a(){var d=$.parseJSON($.cookie("searchbar_cookie")),f=window.location.href.substring(window.location.href.indexOf("/",7)+1,window.location.href.length);if(d){for(var k in d)d[k][0]===serachBar_cookie&&d.splice(k,1);d.length>9&&d.splice(0,1);d.push([serachBar_cookie,f]);k=f="";for(var p=0;p<d.length;p++){k='["'+d[p][0]+'","'+d[p][1]+'"]';f=f!==""?f+","+k:k}f="["+f+"]"}else f='[["'+serachBar_cookie+'","'+f+'"]]';$.cookie("searchbar_cookie",f,{expires:365,path:"/",domain:"5173.com"})}
$(".sort_price_list");var c=$("div.fed-toolstip.yj_tips"),h=false;if(document.cookie.indexOf("gameYXYJ_tips=")==-1)if(c.length>0&&$("li.upper").length>0){c.fedFollow("li.upper",{left:0,top:-100});c.find("a.fed-tipsclose").click(function(d){c.css("display","none");h=true;var f=new Date;f.setTime(f.getTime()+31104E7);document.cookie="gameYXYJ_tips=1; expires="+f.toGMTString()+"; path=/";d.preventDefault()})}var e=function(d,f){var k=document.body,p=document.documentElement,y=!!~navigator.userAgent.toLowerCase().indexOf("msie 6"),
r=d.style,v,s,t,u,q,w,x;if(f){s=f.top;t=f.bottom;u=f.right;q=f.left}else q=s="0px";if(q!==undefined){w="left";u=q}else{w="right";u=u}if(s!==undefined){q="top";x=s}else{q="bottom";x=t}r[w]=u;if(y){if(k.currentStyle.backgroundAttachment!=="fixed"){k.style.backgroundImage="url(about:blank)";k.style.backgroundAttachment="fixed"}if(s!==undefined)f=parseInt(s);else if(t!==undefined){v=d.offsetHeight;f=p.clientHeight-v-parseInt(t);window.onresize=function(){f=p.clientHeight-v-parseInt(t);r.setExpression("top",
"fuckIE6=document.documentElement.scrollTop + "+f+' + "px"')}}r.position="absolute";r.setExpression("top","fuckIE6=document.documentElement.scrollTop + "+f+' + "px"')}else{r.position="fixed";r[q]=x}};if($(".sort_bottom1").length>0)var b=$(".sort_bottom1").eq(0),g=b.offset().top,j=b.outerWidth(),m=b.parent(),n=false;else{b=$(".sort_bottom").eq(0);g=b.offset().top;j=b.outerWidth();m=b.parent();n=false}var i=function(){var d=!!~navigator.userAgent.toLowerCase().indexOf("msie 6");b.css({marginLeft:"",
zIndex:"",position:""}).removeClass("sort_bottom_fixed").prependTo(m);d&&b[0].removeExpression("top")};$(window).bind("scroll.sort",function(){var d=$(this).scrollTop();if(d>g&&!n){n=true;b.css({marginLeft:"-"+j/2+"px",zIndex:"10001"}).addClass("sort_bottom_fixed").appendTo(document.body);e(b[0],{top:"0px",left:"50%"})}else if(d<g&&n){n=false;i()}});b.find("a.close_btn").bind("click",function(d){i();$(window).unbind("scroll.sort");d.preventDefault()});var l=$("#chooseSiblings"),o=l.closest(".sort_bottom_box");
if(o.height()==34)l.hide();else{l.show();l.click(function(){if(l.hasClass("siblings_up")){l.removeClass("siblings_up");l.html("\u6536\u8d77");o.height("auto")}else{l.addClass("siblings_up");l.html("\u5c55\u5f00");o.height(34);o.css("overflow","hidden")}})}({init:function(d){this.top=d.top;this.scroll_top=d.scroll_top;this.fix=d.fix||0;this.url=window.location.href;this.isNew=~this.url.indexOf("list")?true:false;this.isIE6=$.browser.msie&&$.browser.version==="6.0";this.isUrchin=typeof __utmTrackEvent!==
"undefined";this.renderHtml();this.controls()},renderHtml:function(){var d=this,f={text:d.isNew===false?"\u4f7f\u7528\u65b0\u7248":"\u8fd4\u56de\u65e7\u7248",color:d.isNew?"color: #999999;":"color: #f60;",pic:d.isNew?"http://img01.5173cdn.com/search_v3/build/1.00/images/change_v.png":"http://img01.5173cdn.com/search_v3/build/1.00/images/change_v1.png"};f="<style> #qhvBox { cursor: pointer; position: absolute; left: 50%; top: "+d.top+"px; margin-left: 513px; width: 70px; height: 70px; border: 1px solid #e5e5e5; background-color: #fff; "+
f.color+' text-align: center; display: block;margin-top:30px } #qhvBox img { display: block; margin: 13px 22px 10px; } </style> <div id="qhvBox"> <img src="'+f.pic+'" alt="'+f.text+'"/>'+f.text+" </div>";$("body").append(f);var k=$("#qhvBox");d.isIE6?$(window).scroll(function(){$(this).scrollTop()>d.top-d.fix?k.css({top:$(this).scrollTop()+d.scroll_top+"px"}):k.css({top:d.top+"px"})}):$(window).scroll(function(){$(this).scrollTop()>d.top-d.fix?k.css({position:"fixed",top:d.scroll_top+"px"}):k.css({position:"absolute",
top:d.top+"px"})})},controls:function(){function d(){var p=k.url.indexOf("/",7);window.location.href=k.url.substring(0,p)+"/list"+k.url.substring(p,k.url.length)}function f(){k.url=k.url.replace("/list","");window.location.href=k.url}var k=this;$("#qhvBox").bind("click",function(){if(k.isNew){k.isUrchin&&__utmTrackEvent(encodeURIComponent("\u5217\u8868\u9875"),encodeURIComponent("\u5217\u8868\u9875\u5207\u6362"),encodeURIComponent("\u5207\u6362\u81f3\u65e7\u7248"));f()}else{k.isUrchin&&__utmTrackEvent(encodeURIComponent("\u5217\u8868\u9875"),
encodeURIComponent("\u5217\u8868\u9875\u5207\u6362"),encodeURIComponent("\u5207\u6362\u81f3\u65b0\u7248"));d()}})}}).init({top:190,scroll_top:125,fix:140});typeof serachBar_cookie!=="undefined"&&serachBar_cookie!==""&&a();$("#searchSerQuick").keyup(function(){var d=$.trim($(this).val()),f=$(this).parent().next("dl.high_begin_p").find("dt");$.quickSerach.init(f,d)})});
(function(a){a.quickSerach=a.quickSerach||{};a.quickSerach={init:function(c,h){for(var e=a(c).length,b=0,g="";b<e;b++){g=a(c).eq(b).find("a").attr("spell")==undefined?false:a(c).eq(b).find("a").attr("spell").indexOf(h)>-1;a(c).eq(b).find("a").html().indexOf(h)>-1||g?a(c).eq(b).css("display","block"):a(c).eq(b).css("display","none")}}}})(jQuery);
