/*begin
2012-11-09 16:36:40 By wd@5173.com*/
var _uacct="UA-16260521-1",_userv=2,_ufsc=1,_udn=".5173.com",_uhash="off",_utimeout="1800",_ugifpath="http://urchin.5173.com/__utm.gif",_utsp="|",_uflash=1,_utitle=1,_ulink=0,_uanchor=0,_utcp="/",_usample=100,_uctm=1,_ucto="15768000",_uccn="utm_campaign",_ucmd="utm_medium",_ucsr="utm_source",_uctr="utm_term",_ucct="utm_content",_ucid="utm_id",_ucno="utm_nooverride",_uOsr=[],_uOkw=[];_uOsr[0]="google";_uOkw[0]="q";_uOsr[1]="yahoo";_uOkw[1]="p";_uOsr[2]="msn";_uOkw[2]="q";_uOsr[3]="aol";_uOkw[3]="query";
_uOsr[4]="aol";_uOkw[4]="encquery";_uOsr[5]="lycos";_uOkw[5]="query";_uOsr[6]="ask";_uOkw[6]="q";_uOsr[7]="altavista";_uOkw[7]="q";_uOsr[8]="netscape";_uOkw[8]="query";_uOsr[9]="cnn";_uOkw[9]="query";_uOsr[10]="looksmart";_uOkw[10]="qt";_uOsr[11]="about";_uOkw[11]="terms";_uOsr[12]="mamma";_uOkw[12]="query";_uOsr[13]="alltheweb";_uOkw[13]="q";_uOsr[14]="gigablast";_uOkw[14]="q";_uOsr[15]="voila";_uOkw[15]="rdata";_uOsr[16]="virgilio";_uOkw[16]="qs";_uOsr[17]="live";_uOkw[17]="q";_uOsr[18]="baidu";
_uOkw[18]="wd";_uOsr[19]="alice";_uOkw[19]="qs";_uOsr[20]="yandex";_uOkw[20]="text";_uOsr[21]="najdi";_uOkw[21]="q";_uOsr[22]="aol";_uOkw[22]="q";_uOsr[23]="club-internet";_uOkw[23]="query";_uOsr[24]="mama";_uOkw[24]="query";_uOsr[25]="seznam";_uOkw[25]="q";_uOsr[26]="search";_uOkw[26]="q";_uOsr[27]="wp";_uOkw[27]="szukaj";_uOsr[28]="onet";_uOkw[28]="qt";_uOsr[29]="netsprint";_uOkw[29]="q";_uOsr[30]="google.interia";_uOkw[30]="q";_uOsr[31]="szukacz";_uOkw[31]="q";_uOsr[32]="yam";_uOkw[32]="k";
_uOsr[33]="pchome";_uOkw[33]="q";_uOsr[34]="kvasir";_uOkw[34]="searchExpr";_uOsr[35]="sesam";_uOkw[35]="q";_uOsr[36]="ozu";_uOkw[36]="q";_uOsr[37]="terra";_uOkw[37]="query";_uOsr[38]="nostrum";_uOkw[38]="query";_uOsr[39]="mynet";_uOkw[39]="q";_uOsr[40]="ekolay";_uOkw[40]="q";_uOsr[41]="search.ilse";_uOkw[41]="search_for";_uOsr[42]="bing";_uOkw[42]="q";_uOsr[43]="google";_uOkw[43]="as_q";_uOsr[44]="soso";_uOkw[44]="w";_uOsr[45]="youdao";_uOkw[45]="q";_uOsr[46]="sogou";_uOkw[46]="query";_uOsr[47]="vnet";
_uOkw[47]="kw";_uOsr[48]="3721";_uOkw[48]="name";_uOsr[49]="3721";_uOkw[49]="p";_uOsr[50]="gougou";_uOkw[50]="search";_uOsr[51]="118114";_uOkw[51]="kw";_uOsr[52]="m.baidu.com";_uOkw[52]="word";_uOsr[53]="baidu";_uOkw[53]="word";_uOsr[54]="baidu";_uOkw[54]="w";_uOsr[55]="baidu";_uOkw[55]="q1";_uOsr[56]="images.baidu.com";_uOkw[56]="word";_uOsr[57]="ucweb";_uOkw[57]="keyword";_uOsr[58]="ucweb";_uOkw[58]="word";_uOsr[59]="114so";_uOkw[59]="kw";_uOsr[60]="jike";_uOkw[60]="q";_uOsr[61]="so.360.cn";
_uOkw[61]="q";_uOsr[62]="glb.uc.cn";_uOkw[62]="keyword";_uOsr[63]="360sou";_uOkw[63]="q";var _uOno=[];_uOno[0]="5173";_uOno[1]="www.5173.com";_uOno[2]="5173.com";var _uRno=[];_uRno[0]=".5173.com";var _uff,_udh,_udt,_ubl=0,_udo="",_uu,_ufns=0,_uns=0,_ur="-",_ufno=0,_ust=0,_ubd=document,_udl=_ubd.location,_udlh="",_uwv="1",_ugifpath2="http://www.google-analytics.com/__utm.gif";if(_udl.hash)_udlh=_udl.href.substring(_udl.href.indexOf("#"));if(_udl.protocol=="https:")_ugifpath2="https://ssl.google-analytics.com/__utm.gif";
if(!_utcp||_utcp=="")_utcp="/";var _ecm={};_ecm["'"]="'0";_ecm[")"]="'1";_ecm["*"]="'2";_ecm["!"]="'3";
function urchinTracker(a,b){if(_udl.protocol!="file:")if(!(_uff&&(!a||a==""))){var c,e,f,h,d,g,i,k="",j="",m=0,l=" expires="+_uNx()+";";f=_ubd.cookie;_udh=_uDomain();if(_uVG()){_uu=Math.round(Math.random()*2147483647);_udt=new Date;_ust=Math.round(_udt.getTime()/1E3);c=f.indexOf("__utma="+_udh);e=f.indexOf("__utmb="+_udh);f=f.indexOf("__utmc="+_udh);if(_udn&&_udn!="")_udo=" domain="+_udn+";";if(_utimeout&&_utimeout!=""){k=new Date(_udt.getTime()+_utimeout*1E3);k=" expires="+k.toGMTString()+";"}if(_ulink){if(_uanchor&&
_udlh&&_udlh!="")j=_udlh+"&";j+=_udl.search;if(j&&j!=""&&j.indexOf("__utma=")>=0){if(!_uIN(c=_uGC(j,"__utma=","&")))c="-";if(!_uIN(e=_uGC(j,"__utmb=","&")))e="-";if(!_uIN(f=_uGC(j,"__utmc=","&")))f="-";d=_uGC(j,"__utmv=","&");g=_uGC(j,"__utmz=","&");i=_uGC(j,"__utmk=","&");h=_uGC(j,"__utmx=","&");if(i*1!=_uHash(c+e+f+h+g+d)*1+_udh*1){_ubl=1;d=h=f=e=c="-"}if(c!="-"&&e!="-"&&f!="-")m=1;else if(c!="-")m=2}}if(m==1){_ubd.cookie="__utma="+c+"; path="+_utcp+";"+l+_udo;_ubd.cookie="__utmb="+e+"; path="+
_utcp+";"+k+_udo;_ubd.cookie="__utmc="+f+"; path="+_utcp+";"+_udo}else if(m==2){c=_uFixA(j,"&",_ust);_ubd.cookie="__utma="+c+"; path="+_utcp+";"+l+_udo;_ubd.cookie="__utmb="+_udh+"; path="+_utcp+";"+k+_udo;_ubd.cookie="__utmc="+_udh+"; path="+_utcp+";"+_udo;_ufns=1}else if(c>=0&&e>=0&&f>=0)_ubd.cookie="__utmb="+_udh+"; path="+_utcp+";"+k+_udo;else{c=c>=0?_uFixA(_ubd.cookie,";",_ust):_udh+"."+_uu+"."+_ust+"."+_ust+"."+_ust+".1";_ubd.cookie="__utma="+c+"; path="+_utcp+";"+l+_udo;_ubd.cookie="__utmb="+
_udh+"; path="+_utcp+";"+k+_udo;_ubd.cookie="__utmc="+_udh+"; path="+_utcp+";"+_udo;_ufns=1}if(_ulink&&h&&h!=""&&h!="-"){h=_uUES(h);if(h.indexOf(";")==-1)_ubd.cookie="__utmx="+h+"; path="+_utcp+";"+l+_udo}if(_ulink&&d&&d!=""&&d!="-"){d=_uUES(d);if(d.indexOf(";")==-1)_ubd.cookie="__utmv="+d+"; path="+_utcp+";"+l+_udo}_uInfo(a,b);_ufno=_ufns=0;if(!a||a=="")_uff=1}}}
function _uInfo(a,b){var c="",e="",f=_udl.pathname+_udl.search;if(a&&a!="")f=_uES(a,1);_ur=_ubd.referrer;if(!_ur||_ur=="")_ur="-";else{e=_ubd.domain;if(_utcp&&_utcp!="/")e+=_utcp;a=_ur.indexOf(e);if(a>=0&&a<=8)_ur="0";if(_ur.indexOf("[")==0&&_ur.lastIndexOf("]")==_ur.length-1)_ur="-"}c+="&utmn="+_uu;if(b)c+=b;if(_ufsc)c+=_uBInfo();if(_uctm)c+=_uCInfo();if(_utitle&&_ubd.title&&_ubd.title!="")c+="&utmdt="+_uES(_ubd.title);if(_udl.hostname&&_udl.hostname!="")c+="&utmhn="+_uES(_udl.hostname);c+="&utmr="+
_ur;c+="&utmp="+f;if((_userv==0||_userv==2)&&_uSP()){b=new Image(1,1);b.src=_ugifpath+"?utmwv="+_uwv+c;b.onload=function(){_uVoid()}}if((_userv==1||_userv==2)&&_uSP()){b=new Image(1,1);b.src=_ugifpath2+"?utmwv="+_uwv+c+"&utmac="+_uacct+"&utmcc="+_uGCS();b.onload=function(){_uVoid()}}}function _uVoid(){}
function _uCInfo(){if(!_ucto||_ucto=="")_ucto="15768000";if(_uVG()){var a="",b="-",c="-",e="-",f=0,h=0,d=0;c=0;var g="-",i="";if(_uanchor&&_udlh&&_udlh!="")i=_udlh+"&";i+=_udl.search;var k=new Date(_udt.getTime()+_ucto*1E3),j=_ubd.cookie;k=" expires="+k.toGMTString()+";";if(_ulink&&!_ubl){g=_uUES(_uGC(i,"__utmz=","&"));if(g!="-"&&g.indexOf(";")==-1){_ubd.cookie="__utmz="+g+"; path="+_utcp+";"+k+_udo;return""}}g=j.indexOf("__utmz="+_udh);g=g>-1?_uGC(j,"__utmz="+_udh,";"):"-";b=_uGC(i,_ucid+"=","&");
c=_uGC(i,_ucsr+"=","&");e=_uGC(i,"gclid=","&");if(b!="-"&&b!=""||c!="-"&&c!=""||e!="-"&&e!=""){if(b!="-"&&b!="")a+="utmcid="+_uEC(b);if(c!="-"&&c!=""){if(a!="")a+="|";a+="utmcsr="+_uEC(c)}if(e!="-"&&e!=""){if(a!="")a+="|";a+="utmgclid="+_uEC(e)}b=_uGC(i,_uccn+"=","&");a+=b!="-"&&b!=""?"|utmccn="+_uEC(b):"|utmccn=(not+set)";b=_uGC(i,_ucmd+"=","&");a+=b!="-"&&b!=""?"|utmcmd="+_uEC(b):"|utmcmd=(not+set)";b=_uGC(i,_uctr+"=","&");if(b!="-"&&b!="")a+="|utmctr="+_uEC(b);else{b=_uOrg(1);if(b!="-"&&b!="")a+=
"|utmctr="+_uEC(b)}b=_uGC(i,_ucct+"=","&");if(b!="-"&&b!="")a+="|utmcct="+_uEC(b);b=_uGC(i,_ucno+"=","&");if(b=="1")f=1;if(g!="-"&&f==1)return""}if(a=="-"||a==""){a=_uOrg();if(g!="-"&&_ufno==1)return""}if(a=="-"||a==""){if(_ufns==1)a=_uRef();if(g!="-"&&_ufno==1)return""}if(a=="-"||a==""){if(g=="-"&&_ufns==1)a="utmccn=(direct)|utmcsr=(direct)|utmcmd=(none)";if(a=="-"||a=="")return""}if(g!="-"){c=g.indexOf(".");if(c>-1)c=g.indexOf(".",c+1);if(c>-1)c=g.indexOf(".",c+1);if(c>-1)c=g.indexOf(".",c+1);b=
g.substring(c+1,g.length);if(b.toLowerCase()==a.toLowerCase())h=1;b=g.substring(0,c);if((c=b.lastIndexOf("."))>-1){b=b.substring(c+1,b.length);d=b*1}}if(h==0||_ufns==1){b=_uGC(j,"__utma="+_udh,";");if((c=b.lastIndexOf("."))>9){_uns=b.substring(c+1,b.length);_uns*=1}d++;if(_uns==0)_uns=1;_ubd.cookie="__utmz="+_udh+"."+_ust+"."+_uns+"."+d+"."+a+"; path="+_utcp+"; "+k+_udo}return h==0||_ufns==1?"&utmcn=1":"&utmcr=1"}}
function _uRef(){if(_ur=="0"||_ur==""||_ur=="-")return"";var a=0,b,c,e;if((a=_ur.indexOf("://"))<0)return"";b=_ur.substring(a+3,_ur.length);if(b.indexOf("/")>-1){c=b.substring(b.indexOf("/"),b.length);if(c.indexOf("?")>-1)c=c.substring(0,c.indexOf("?"));b=b.substring(0,b.indexOf("/"))}e=b=b.toLowerCase();if((a=e.indexOf(":"))>-1)e=e.substring(0,a);for(var f=0;f<_uRno.length;f++)if((a=e.indexOf(_uRno[f].toLowerCase()))>-1&&e.length==a+_uRno[f].length){_ufno=1;break}if(b.indexOf("www.")==0)b=b.substring(4,
b.length);return"utmccn=(referral)|utmcsr="+_uEC(b)+"|utmcct="+_uEC(c)+"|utmcmd=referral"}
function _uOrg(a){if(_ur=="0"||_ur==""||_ur=="-")return"";var b=0,c;if((b=_ur.indexOf("://"))<0)return"";c=_ur.substring(b+3,_ur.length);if(c.indexOf("/")>-1)c=c.substring(0,c.indexOf("/"));for(var e=0;e<_uOsr.length;e++)if(c.toLowerCase().indexOf(_uOsr[e].toLowerCase())>-1)if((b=_ur.indexOf("?"+_uOkw[e]+"="))>-1||(b=_ur.indexOf("&"+_uOkw[e]+"="))>-1){c=_ur.substring(b+_uOkw[e].length+2,_ur.length);if((b=c.indexOf("&"))>-1)c=c.substring(0,b);for(b=0;b<_uOno.length;b++)if(_uOno[b].toLowerCase()==c.toLowerCase()){_ufno=
1;break}return a?_uEC(c):"utmccn=(organic)|utmcsr="+_uEC(_uOsr[e])+"|utmctr="+_uEC(c)+"|utmcmd=organic"}return""}
function _uBInfo(){var a="-",b="-",c="-",e="-",f="-",h=1;h=navigator;if(self.screen){a=screen.width+"x"+screen.height;b=screen.colorDepth+"-bit"}else if(self.java){a=java.awt.Toolkit.getDefaultToolkit().getScreenSize();a=a.width+"x"+a.height}if(h.language)c=h.language.toLowerCase();else if(h.browserLanguage)c=h.browserLanguage.toLowerCase();h=h.javaEnabled()?1:0;if(_uflash)e=_uFlash();if(_ubd.characterSet)f=_uES(_ubd.characterSet);else if(_ubd.charset)f=_uES(_ubd.charset);return"&utmcs="+f+"&utmsr="+
a+"&utmsc="+b+"&utmul="+c+"&utmje="+h+"&utmfl="+e}
function __utmSetTrans(){var a;if(_ubd.getElementById)a=_ubd.getElementById("utmtrans");else if(_ubd.utmform&&_ubd.utmform.utmtrans)a=_ubd.utmform.utmtrans;if(a){a=a.value.split("UTM:");var b,c,e;if(_userv==0||_userv==2)b=[];if(_userv==1||_userv==2){c=[];e=_uGCS()}for(var f=0;f<a.length;f++){a[f]=_uTrim(a[f]);if(!(a[f].charAt(0)!="T"&&a[f].charAt(0)!="I")){var h=Math.round(Math.random()*2147483647);if(!_utsp||_utsp=="")_utsp="|";var d=a[f].split(_utsp),g="";if(d[0].charAt(0)=="T"){g="&utmt=tran&utmn="+
h;d[1]=_uTrim(d[1]);if(d[1]&&d[1]!="")g+="&utmtid="+_uES(d[1]);d[2]=_uTrim(d[2]);if(d[2]&&d[2]!="")g+="&utmtst="+_uES(d[2]);d[3]=_uTrim(d[3]);if(d[3]&&d[3]!="")g+="&utmtto="+_uES(d[3]);d[4]=_uTrim(d[4]);if(d[4]&&d[4]!="")g+="&utmttx="+_uES(d[4]);d[5]=_uTrim(d[5]);if(d[5]&&d[5]!="")g+="&utmtsp="+_uES(d[5]);d[6]=_uTrim(d[6]);if(d[6]&&d[6]!="")g+="&utmtci="+_uES(d[6]);d[7]=_uTrim(d[7]);if(d[7]&&d[7]!="")g+="&utmtrg="+_uES(d[7]);d[8]=_uTrim(d[8]);if(d[8]&&d[8]!="")g+="&utmtco="+_uES(d[8])}else{g="&utmt=item&utmn="+
h;d[1]=_uTrim(d[1]);if(d[1]&&d[1]!="")g+="&utmtid="+_uES(d[1]);d[2]=_uTrim(d[2]);if(d[2]&&d[2]!="")g+="&utmipc="+_uES(d[2]);d[3]=_uTrim(d[3]);if(d[3]&&d[3]!="")g+="&utmipn="+_uES(d[3]);d[4]=_uTrim(d[4]);if(d[4]&&d[4]!="")g+="&utmiva="+_uES(d[4]);d[5]=_uTrim(d[5]);if(d[5]&&d[5]!="")g+="&utmipr="+_uES(d[5]);d[6]=_uTrim(d[6]);if(d[6]&&d[6]!="")g+="&utmiqt="+_uES(d[6])}if((_userv==0||_userv==2)&&_uSP()){b[f]=new Image(1,1);b[f].src=_ugifpath+"?utmwv="+_uwv+g;b[f].onload=function(){_uVoid()}}if((_userv==
1||_userv==2)&&_uSP()){c[f]=new Image(1,1);c[f].src=_ugifpath2+"?utmwv="+_uwv+g+"&utmac="+_uacct+"&utmcc="+e;c[f].onload=function(){_uVoid()}}}}}}
function _uFlash(){var a="-",b=navigator;if(b.plugins&&b.plugins.length)for(var c=0;c<b.plugins.length;c++){if(b.plugins[c].name.indexOf("Shockwave Flash")!=-1){a=b.plugins[c].description.split("Shockwave Flash ")[1];break}}else if(window.ActiveXObject)for(c=10;c>=2;c--)try{if(eval("new ActiveXObject('ShockwaveFlash.ShockwaveFlash."+c+"');")){a=c+".0";break}}catch(e){}return a}
function __utmLinker(a,b){if(_ulink){var c,e="-",f="-",h="-",d="-",g="-",i="-";i=_ubd.cookie;if(!(!a||a=="")){var k=a.indexOf("?"),j=a.indexOf("#");if(i){e=_uES(_uGC(i,"__utma="+_udh,";"));f=_uES(_uGC(i,"__utmb="+_udh,";"));h=_uES(_uGC(i,"__utmc="+_udh,";"));d=_uES(_uGC(i,"__utmx="+_udh,";"));g=_uES(_uGC(i,"__utmz="+_udh,";"));i=_uES(_uGC(i,"__utmv="+_udh,";"));c=_uHash(e+f+h+d+g+i)*1+_udh*1;c="__utma="+e+"&__utmb="+f+"&__utmc="+h+"&__utmx="+d+"&__utmz="+g+"&__utmv="+i+"&__utmk="+c}if(c){if(!(b&&
j>-1))_udl.href=b?a+"#"+c:k==-1&&j==-1?a+"?"+c:j==-1?a+"&"+c:k==-1?a.substring(0,j-1)+"?"+c+a.substring(j):a.substring(0,j-1)+"&"+c+a.substring(j)}else _udl.href=a}}}
function __utmLinkPost(a,b){if(_ulink){var c,e="-",f="-",h="-",d="-",g="-",i="-";i=_ubd.cookie;if(a&&a.action){var k=a.action.indexOf("?"),j=a.action.indexOf("#");if(i){e=_uES(_uGC(i,"__utma="+_udh,";"));f=_uES(_uGC(i,"__utmb="+_udh,";"));h=_uES(_uGC(i,"__utmc="+_udh,";"));d=_uES(_uGC(i,"__utmx="+_udh,";"));g=_uES(_uGC(i,"__utmz="+_udh,";"));i=_uES(_uGC(i,"__utmv="+_udh,";"));c=_uHash(e+f+h+d+g+i)*1+_udh*1;c="__utma="+e+"&__utmb="+f+"&__utmc="+h+"&__utmx="+d+"&__utmz="+g+"&__utmv="+i+"&__utmk="+c}if(c)if(!(b&&
j>-1))if(b)a.action+="#"+c;else if(k==-1&&j==-1)a.action+="?"+c;else if(j==-1)a.action+="&"+c;else a.action=k==-1?a.action.substring(0,j-1)+"?"+c+a.action.substring(j):a.action.substring(0,j-1)+"&"+c+a.action.substring(j)}}}
function __utmSetVar(a){if(!(!a||a=="")){if(!_udo||_udo==""){_udh=_uDomain();if(_udn&&_udn!="")_udo=" domain="+_udn+";"}if(_uVG()){var b=Math.round(Math.random()*2147483647);_ubd.cookie="__utmv="+_udh+"."+_uES(a)+"; path="+_utcp+"; expires="+_uNx()+";"+_udo;a="&utmt=var&utmn="+b;if((_userv==0||_userv==2)&&_uSP()){b=new Image(1,1);b.src=_ugifpath+"?utmwv="+_uwv+a;b.onload=function(){_uVoid()}}if((_userv==1||_userv==2)&&_uSP()){b=new Image(1,1);b.src=_ugifpath2+"?utmwv="+_uwv+a+"&utmac="+_uacct+"&utmcc="+
_uGCS();b.onload=function(){_uVoid()}}}}}function __utmTrackEvent(a,b,c,e,f){if(!(!a||a==""||!b||b=="")){f=f;var h="";if(!f||f=="")f=_udl.pathname+_udl.search;h+="&utmt=event&utme=5("+_UEE(a)+"*"+_UEE(b);if(c&&c!="")h+="*"+c;h+=")";if(e&&e!="")h+="("+e+")";urchinTracker(f,h)}}
function _uGCS(){var a,b="",c=_ubd.cookie;if((a=_uGC(c,"__utma="+_udh,";"))!="-")b+=_uES("__utma="+a+";+");if((a=_uGC(c,"__utmb="+_udh,";"))!="-")b+=_uES("__utmb="+a+";+");if((a=_uGC(c,"__utmc="+_udh,";"))!="-")b+=_uES("__utmc="+a+";+");if((a=_uGC(c,"__utmx="+_udh,";"))!="-")b+=_uES("__utmx="+a+";+");if((a=_uGC(c,"__utmz="+_udh,";"))!="-")b+=_uES("__utmz="+a+";+");if((a=_uGC(c,"__utmv="+_udh,";"))!="-")b+=_uES("__utmv="+a+";");if(b.charAt(b.length-1)=="+")b=b.substring(0,b.length-1);return b}
function _uGC(a,b,c){if(!a||a==""||!b||b==""||!c||c=="")return"-";var e,f="-";e=a.indexOf(b);b=b.indexOf("=")+1;if(e>-1){c=a.indexOf(c,e);if(c<0)c=a.length;f=a.substring(e+b,c)}return f}function _uDomain(){if(!_udn||_udn==""||_udn=="none"){_udn="";return 1}if(_udn=="auto"){var a=_ubd.domain;if(a.substring(0,4)=="www.")a=a.substring(4,a.length);_udn=a}_udn=_udn.toLowerCase();if(_uhash=="off")return 12194411;return _uHash(_udn)}
function _uHash(a){if(!a||a=="")return 1;for(var b=0,c=0,e=a.length-1;e>=0;e--){c=parseInt(a.charCodeAt(e));b=(b<<6&268435455)+c+(c<<14);if((c=b&266338304)!=0)b^=c>>21}return b}
function _uFixA(a,b,c){if(!a||a==""||!b||b==""||!c||c=="")return"-";a=_uGC(a,"__utma="+_udh,b);var e=b=0;if((e=a.lastIndexOf("."))>9){_uns=a.substring(e+1,a.length);_uns=_uns*1+1;a=a.substring(0,e);if((e=a.lastIndexOf("."))>7){b=a.substring(e+1,a.length);a=a.substring(0,e)}if((e=a.lastIndexOf("."))>5)a=a.substring(0,e);a+="."+b+"."+c+"."+_uns}return a}
function _uTrim(a){if(!a||a=="")return"";for(;a.charAt(0)==" "||a.charAt(0)=="\n"||a.charAt(0,1)=="\r";)a=a.substring(1,a.length);for(;a.charAt(a.length-1)==" "||a.charAt(a.length-1)=="\n"||a.charAt(a.length-1)=="\r";)a=a.substring(0,a.length-1);return a}function _uEC(a){var b="";if(!a||a=="")return"";for(var c=0;c<a.length;c++)b+=a.charAt(c)==" "?"+":a.charAt(c);return b}
function __utmVisitorCode(a){var b=0,c=0,e=c=0,f=_uGC(_ubd.cookie,"__utma="+_udh,";");if(!((c=f.indexOf(".",0))<0)){if((e=f.indexOf(".",c+1))>0)b=f.substring(c+1,e);else return"";if((c=f.indexOf(".",e+1))>0)c=f.substring(e+1,c);else return"";if(a)return b;else{a=new Array("A","B","C","D","E","F","G","H","J","K","L","M","N","P","R","S","T","U","V","W","X","Y","Z","1","2","3","4","5","6","7","8","9");return a[b>>28&31]+a[b>>23&31]+a[b>>18&31]+a[b>>13&31]+"-"+a[b>>8&31]+a[b>>3&31]+a[((b&7)<<2)+(c>>30&
3)]+a[c>>25&31]+a[c>>20&31]+"-"+a[c>>15&31]+a[c>>10&31]+a[c>>5&31]+a[c&31]}}}function _uIN(a){if(!a)return false;for(var b=0;b<a.length;b++){var c=a.charAt(b);if((c<"0"||c>"9")&&c!=".")return false}return true}function _UEE(a){var b="",c,e,f;if(!a||a=="")return"";for(c=0;c<a.length;c++){e=a.charAt(c);f=_ecm[e];b+=undefined!=f?f:e}return b}function _uES(a,b){return typeof encodeURIComponent=="function"?b?encodeURI(a):encodeURIComponent(a):escape(a)}
function _uUES(a){return typeof decodeURIComponent=="function"?decodeURIComponent(a):unescape(a)}function _uVG(){if((_udn.indexOf("www.google.")==0||_udn.indexOf(".google.")==0||_udn.indexOf("google.")==0)&&_utcp=="/"&&_udn.indexOf("google.org")==-1)return false;return true}function _uSP(){var a=100;if(_usample)a=_usample;if(a>=100||a<=0)return true;return __utmVisitorCode(1)%1E4<a*100}
function urchinPathCopy(a){var b=document,c,e,f,h,d,g,i,k,j;g=new Array("a","b","c","v","x","z");k=_uDomain();if(_udn&&_udn!="")j=" domain="+_udn+";";c=_uNx()+";";e=new Date;e.setTime(e.getTime()+_utimeout*1E3);e=e.toGMTString()+";";f=new Date;f.setTime(f.getTime()+_ucto*1E3);f=f.toGMTString()+";";for(h=0;h<6;h++){i=" expires=";if(h==1)i+=e;else if(h==2)i="";else i+=h==5?f:c;d=_uGC(b.cookie,"__utm"+g[h]+"="+k,";");if(d!="-")b.cookie="__utm"+g[h]+"="+d+"; path="+a+";"+i+j}}
function _uCO(){if(!(!_utk||_utk==""||_utk.length<10)){var a="www.google.com";if(_utk.charAt(0)=="!")a="analytics.corp.google.com";_ubd.cookie="GASO="+_utk+"; path="+_utcp+";"+_udo;var b=document.createElement("script");b.type="text/javascript";b.id="_gasojs";b.src="https://"+a+"/analytics/reporting/overlay_js?gaso="+_utk+"&"+Math.random();document.getElementsByTagName("head")[0].appendChild(b)}}
function _uGT(){var a=location.hash;return a&&a!=""&&a.indexOf("#gaso=")==0?_uGC(a,"gaso=","&"):_uGC(_ubd.cookie,"GASO=",";")}var _utk=_uGT();if(_utk&&_utk!=""&&_utk.length>10)if(window.addEventListener)window.addEventListener("load",_uCO,false);else window.attachEvent&&window.attachEvent("onload",_uCO);function _uNx(){return(new Date((new Date).getTime()+63072E6)).toGMTString()};
